name: lughafy
description: Kenya's 68-language AI translator. Offline. Real-time. Built by saytekaren.

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.6.1
  flutter_tts: ^3.8.5
  google_ml_kit: ^0.16.0
  onnxruntime: ^0.2.1
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/models/
